<a href="https://colab.research.google.com/github/harishvenkatram/data-science-101-b1-Nov20/blob/main/Day3-11th%20Nov'20%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Questions 1
#Solution
import numpy as np
np.arange(2,51,3,int)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [ ]:
#Question 2
#Solution
import numpy as np
list1=[]
list2=[]
print("Enter 5 elements in first list")
for i in range(5):
  a=int(input())
  list1.append(a)
  i+=1
arr1=np.array(list1)
print("Enter 5 elements in second list")
for j in range(5):
  b=int(input())
  list2.append(b)
  j+=1
arr2=np.array(list2)
arr=np.concatenate((arr1,arr2))
print("Concatenated Array: ",arr)
print("Sorted Arrays: ",np.sort(arr))

Enter 5 elements in first list
23
56
12
4
53
Enter 5 elements in second list
9
6
56
11
18
Concatenated Array:  [23 56 12  4 53  9  6 56 11 18]
Sorted Arrays:  [ 4  6  9 11 12 18 23 53 56 56]


In [15]:
#Question 3
#Solution
import numpy as np
arr = ( [[ 1, 2, 3],[ 4, 2, 5]] )  
# Printing array dimensions (axes)
print("No. of dimensions: ", np.ndim(arr))
# Printing size (total number of elements) of array
print("Size of array: ", np.size(arr))

No. of dimensions:  2
Size of array:  6


In [ ]:
#Question 4
#Solution
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print(arr.shape)
twod= arr[np.newaxis, :]
print(twod.shape)


(10,)
(1, 10)


In [12]:
#Question 5
#Solution
import numpy as np
arr1=[[1,2],[3,4]]
arr2=[[5,6],[7,8]]
print("Array 1:",arr1,"\nArray 2:",arr2)
#Vertical display of array
ver=np.vstack((arr1,arr2))
print ("\nOutput vertically stacked array:\n",ver)
#Vertical display of array
hor=np.hstack((arr1,arr2))
print ("\nOutput horizontally stacked array:\n",hor)

Array 1: [[1, 2], [3, 4]] 
Array 2: [[5, 6], [7, 8]]

Output vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Output horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]


In [22]:
#Question 6
#Solution
import numpy as np
arr=[1,1,2,3,4,4,1,1,1,1,2,2,2,5,25,1,1]
(unique, count)=np.unique(arr,return_counts=True)
freq=np.asarray((unique, count)).T
print(freq)

[[ 1  8]
 [ 2  4]
 [ 3  1]
 [ 4  2]
 [ 5  1]
 [25  1]]
